"""Populate source README files with scrape requirements."""

from __future__ import annotations

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[2]

TEMPLATE = """# {name}

- Region: {region}
- Country: {country}
- Coverage: {coverage}

## Access
- URL: {url}
- Access method: {method}
- Recommended rate limit: {rate_limit}
- Authentication: {auth}

## Legal & Compliance
- Reference: {legal_url}
- Notes: {legal_notes}

## Implementation Notes
{notes}
"""

SOURCES = [
    {
        "path": "data/raw/north_america/canada/college_des_medecins_du_quebec/README.md",
        "name": "College des medecins du Quebec",
        "region": "North America",
        "country": "Canada",
        "coverage": "Excellent, provincial but consistent",
        "url": "https://www.cmq.org/bottin?sc_lang=en",
        "method": "Public searchable register with CSV export after accepting terms",
        "rate_limit": "1 request per second; sleep 5 seconds between CSV pulls",
        "auth": "Session cookie stored after accepting legal notice",
        "legal_url": "https://www.cmq.org/en/a-propos/politique-du-site-web.aspx",
        "legal_notes": "Respect CMQ website policy and attribute CMQ as the source.",
        "notes": "- Store daily CSV snapshots as cmq_YYYYMMDD.csv\n- Log download metadata in data/metadata/scrape_log.csv\n- Monitor CMQ news feed for schema revisions",
    },
    {
        "path": "data/raw/north_america/canada/college_of_physicians_and_surgeons_of_ontario/README.md",
        "name": "College of Physicians and Surgeons of Ontario",
        "region": "North America",
        "country": "Canada",
        "coverage": "Excellent, provincial but consistent",
        "url": "https://doctors.cpso.on.ca/",
        "method": "HTML search endpoint with JSON POST (GetDoctors) payloads for pagination",
        "rate_limit": "1 request per second per endpoint; rotate user agents hourly",
        "auth": "None, but anti-bot JavaScript requires realistic headers",
        "legal_url": "https://www.cpso.on.ca/Footer-Pages/Privacy/Terms-of-Use",
        "legal_notes": "CPSO restricts commercial reuse; cite CPSO and include retrieval date.",
        "notes": "- Persist raw JSON pages before normalization\n- Capture physician profile URLs for deep-link verification\n- Reconcile CPSO number to canonical physician_id",
    },
    {
        "path": "data/raw/north_america/canada/college_of_physicians_and_surgeons_of_british_columbia/README.md",
        "name": "College of Physicians and Surgeons of British Columbia",
        "region": "North America",
        "country": "Canada",
        "coverage": "Excellent, provincial but consistent",
        "url": "https://www.cpsbc.ca/physician_directory",
        "method": "Form-based search backed by JSON API (endpoint /physician_directory/search)",
        "rate_limit": "0.5 requests per second; rotate IP if blocked",
        "auth": "None; include Referer header matching cpsbc.ca",
        "legal_url": "https://www.cpsbc.ca/terms-use",
        "legal_notes": "Follow CPSBC terms forbidding misuse or misrepresentation of register data.",
        "notes": "- Archive request payloads for reproducibility\n- Capture status history when available\n- Map CPSBC specialties to canonical codes",
    },
    {
        "path": "data/raw/north_america/canada/college_of_physicians_and_surgeons_of_alberta/README.md",
        "name": "College of Physicians and Surgeons of Alberta",
        "region": "North America",
        "country": "Canada",
        "coverage": "Excellent, provincial but consistent",
        "url": "https://search.cpsa.ca/PhysicianSearch",
        "method": "AJAX search returning JSON blocks via /PhysicianSearch/Lookup",
        "rate_limit": "1 request every 2 seconds; obey Retry-After headers",
        "auth": "Anonymous; maintain ASP.NET session cookie",
        "legal_url": "https://cpsa.ca/privacy-terms/",
        "legal_notes": "Use data only for transparency purposes; cite CPSA as source.",
        "notes": "- Fetch alphabetically to avoid server throttling\n- Track practice location coordinates when present\n- Ensure inactive records remain for longitudinal audits",
    },
    {
        "path": "data/raw/north_america/canada/royal_college_of_physicians_and_surgeons_of_canada/README.md",
        "name": "Royal College of Physicians and Surgeons of Canada",
        "region": "North America",
        "country": "Canada",
        "coverage": "Excellent certification coverage (non-licensing)",
        "url": "https://www.royalcollege.ca/rcsite/specialty-certification/certified-specialist-directory-e",
        "method": "POST search form returning HTML tables; parse with BeautifulSoup",
        "rate_limit": "1 request per second; pause 10 seconds per 100 results",
        "auth": "None",
        "legal_url": "https://www.royalcollege.ca/rcsite/terms-and-conditions-e",
        "legal_notes": "Directory may only confirm certification status; include attribution.",
        "notes": "- Use certification data as join table, not licensing authority\n- Capture specialty, subspecialty, and certification year\n- Flag entries for revalidation when specialty list changes",
    },
    {
        "path": "data/raw/north_america/united_states/federation_of_state_medical_boards/README.md",
        "name": "Federation of State Medical Boards",
        "region": "North America",
        "country": "United States",
        "coverage": "High but fragmented; acts as an index",
        "url": "https://www.fsmb.org/contact-a-state-medical-board/",
        "method": "Static HTML directory; scrape board metadata and licensing URLs",
        "rate_limit": "Static page; single fetch per release",
        "auth": "None",
        "legal_url": "https://www.fsmb.org/terms-of-use/",
        "legal_notes": "FSMB material is informational; respect copyrights on proprietary reports.",
        "notes": "- Use output to drive per-state job scheduling\n- Include contact emails and phone numbers for escalation\n- Track state portal authentication requirements",
    },
    {
        "path": "data/raw/north_america/united_states/state_medical_boards/README.md",
        "name": "United States State Medical Boards",
        "region": "North America",
        "country": "United States",
        "coverage": "High, but each board varies in format and cadence",
        "url": "https://www.fsmb.org/contact-a-state-medical-board/",
        "method": "Refer to individual board portals (CSV, HTML, PDF, or SOAP APIs)",
        "rate_limit": "Default to 1 request per second per board until policy reviewed",
        "auth": "Varies: some require CAPTCHA or portal accounts",
        "legal_url": "Board-specific terms (see respective portal footers)",
        "legal_notes": "Confirm statutory allowances for automated access before scraping each board.",
        "notes": "- Create subdirectories per state abbreviation\n- Store portal policy snapshots for compliance audits\n- Document blockers (CAPTCHA, paywalls, FOIA only)",
    },
    {
        "path": "data/raw/north_america/mexico/direccion_general_de_profesiones/README.md",
        "name": "Direccion General de Profesiones",
        "region": "North America",
        "country": "Mexico",
        "coverage": "Partial; national professional license lookup",
        "url": "https://www.gob.mx/cedulaprof",
        "method": "Browser automation posting CURP/name to cedula lookup JSON endpoint",
        "rate_limit": "1 request every 3 seconds; portal throttles bursts",
        "auth": "Requires reCAPTCHA token; integrate manual solving queue",
        "legal_url": "https://www.gob.mx/terminos",
        "legal_notes": "Federal portal terms restrict commercial resale and mandate attribution.",
        "notes": "- Store raw JSON payloads per query\n- Maintain mapping between cedula number and physician_id\n- Document CAPTCHA solving cost and throughput",
    },
    {
        "path": "data/raw/europe/united_kingdom_and_ireland/general_medical_council/README.md",
        "name": "General Medical Council",
        "region": "Europe",
        "country": "United Kingdom",
        "coverage": "Excellent national register",
        "url": "https://www.gmc-uk.org/registration-and-licensing/the-medical-register",
        "method": "JSON API (`/api/gmc/Registrations`) backing advanced search",
        "rate_limit": "5 requests per second allowed; keep concurrency <=2",
        "auth": "None; include standard browser headers",
        "legal_url": "https://www.gmc-uk.org/using-our-site/website-terms-and-conditions",
        "legal_notes": "Reuse permitted for transparency with attribution; no implying GMC endorsement.",
        "notes": "- Fetch by alphabetical batch to avoid missing records\n- Capture license status history and sanctions\n- Map GMC reference number to canonical IDs",
    },
    {
        "path": "data/raw/europe/united_kingdom_and_ireland/irish_medical_council/README.md",
        "name": "Irish Medical Council",
        "region": "Europe",
        "country": "Ireland",
        "coverage": "Excellent national register",
        "url": "https://www.medicalcouncil.ie/public-information/check-the-register/",
        "method": "AJAX request to `/RegisterSearch/api/Doctors` returning JSON",
        "rate_limit": "1 request per second; avoid parallel pagination",
        "auth": "None, but requires anti-forgery token extracted from landing page",
        "legal_url": "https://www.medicalcouncil.ie/footer/terms-conditions/",
        "legal_notes": "Terms permit verification use; redistribution must cite Medical Council.",
        "notes": "- Persist anti-forgery token per run\n- Capture registration division and specialty\n- Track voluntary withdrawal notices",
    },
    {
        "path": "data/raw/europe/france/conseil_national_de_l_ordre_des_medecins/README.md",
        "name": "Conseil National de l'Ordre des Medecins",
        "region": "Europe",
        "country": "France",
        "coverage": "Excellent with rich physician detail",
        "url": "https://www.conseil-national.medecin.fr/le-tableau",
        "method": "GraphQL API powering tableau search; inspect network calls to `/graphql`",
        "rate_limit": "1 request per second; abide by rate headers",
        "auth": "Session cookie plus CSRF token",
        "legal_url": "https://www.conseil-national.medecin.fr/mentions-legales",
        "legal_notes": "Data protected by French reuse rules; cite CNOM and respect GDPR obligations.",
        "notes": "- Store French-language fields plus normalized English equivalents\n- Capture practice addresses and RPPS identifiers\n- Add job to translate specialty labels to canonical codes",
    },
    {
        "path": "data/raw/europe/germany/bundesaerztekammer/README.md",
        "name": "Bundesarztekammer",
        "region": "Europe",
        "country": "Germany",
        "coverage": "Good but decentralized via state chambers",
        "url": "https://www.bundesaerztekammer.de/aerzteschaft/landesaerztekammern/",
        "method": "Scrape list of Landesaerztekammer portals; downstream jobs pull each register",
        "rate_limit": "Static listing; refresh monthly",
        "auth": "None",
        "legal_url": "https://www.bundesaerztekammer.de/footer/impressum/",
        "legal_notes": "Follow federal and state data protection guidance before automation.",
        "notes": "- Maintain mapping of state-level identifiers to canonical IDs\n- Record whether bulk downloads or FOIA needed per state\n- Capture contact info for consent management",
    },
    {
        "path": "data/raw/europe/netherlands/big_register/README.md",
        "name": "BIG Register",
        "region": "Europe",
        "country": "Netherlands",
        "coverage": "Excellent national register",
        "url": "https://www.bigregister.nl/zoek-zorgverlener",
        "method": "JSON API `/api/Registrations` with pagination tokens",
        "rate_limit": "2 requests per second; throttle harder during business hours",
        "auth": "None, but requires Accept-Language header",
        "legal_url": "https://www.bigregister.nl/footer/disclaimer",
        "legal_notes": "Reuse allowed with attribution and without altering context.",
        "notes": "- Capture BIG number, profession, and validity dates\n- Record language of response for audit\n- Normalize municipality codes",
    },
    {
        "path": "data/raw/europe/spain/organizacion_medica_colegial/README.md",
        "name": "Organizacion Medica Colegial",
        "region": "Europe",
        "country": "Spain",
        "coverage": "Good national coverage",
        "url": "https://www.cgcom.es/colegiados",
        "method": "HTML form posts to provincial council endpoints; requires per-college scraping",
        "rate_limit": "1 request per 3 seconds per provincial endpoint",
        "auth": "None",
        "legal_url": "https://www.cgcom.es/aviso-legal",
        "legal_notes": "Respect Spanish data reuse law and cite CGCOM.",
        "notes": "- Track which colegios provide bulk CSV\n- Normalize collegiate numbers and province codes\n- Document gaps for provinces lacking automation",
    },
    {
        "path": "data/raw/europe/italy/federazione_nazionale_degli_ordini_dei_medici/README.md",
        "name": "Federazione Nazionale degli Ordini dei Medici",
        "region": "Europe",
        "country": "Italy",
        "coverage": "Good national coverage",
        "url": "https://portale.fnomceo.it/ricerca-anagrafica/",
        "method": "HTML search with underlying JSON POST at `/wp-json/fnomceo/v1/medici`",
        "rate_limit": "1 request per second; rotate user agents for long runs",
        "auth": "None, but uses nonce token in request headers",
        "legal_url": "https://portale.fnomceo.it/note-legali/",
        "legal_notes": "Reuse allowed for transparency if source credited and context preserved.",
        "notes": "- Capture provincial order code and registration number\n- Store raw Italian field labels for translators\n- Track validation status for each physician",
    },
    {
        "path": "data/raw/europe/portugal/ordem_dos_medicos/README.md",
        "name": "Ordem dos Medicos",
        "region": "Europe",
        "country": "Portugal",
        "coverage": "Good national coverage",
        "url": "https://www.ordemdosmedicos.pt/ver-medico/",
        "method": "Search form posting to `/ver-medico/` with query parameters",
        "rate_limit": "1 request per second; respect caching headers",
        "auth": "None",
        "legal_url": "https://www.ordemdosmedicos.pt/politica-de-privacidade/",
        "legal_notes": "Portuguese privacy policy requires attribution and lawful purpose.",
        "notes": "- Normalize OM numbers\n- Translate specialty strings to canonical codes\n- Capture public disciplinary notes when present",
    },
    {
        "path": "data/raw/europe/belgium/ordre_des_medecins/README.md",
        "name": "Ordre des Medecins (Belgium)",
        "region": "Europe",
        "country": "Belgium",
        "coverage": "Good national coverage",
        "url": "https://www.ordomedic.be/fr/medecins/registre",
        "method": "Server-rendered HTML list with filters; requires pagination crawling",
        "rate_limit": "1 request every 2 seconds; site blocks aggressive bots",
        "auth": "None",
        "legal_url": "https://www.ordomedic.be/fr/disclaimer",
        "legal_notes": "Respect bilingual presentation and cite Ordre/Orde appropriately.",
        "notes": "- Capture both French and Dutch field variants\n- Map national numbers to canonical IDs\n- Preserve specialty board memberships",
    },
    {
        "path": "data/raw/europe/switzerland/medreg/README.md",
        "name": "MedReg",
        "region": "Europe",
        "country": "Switzerland",
        "coverage": "Very good national coverage",
        "url": "https://www.medregom.admin.ch/CRS/",
        "method": "Public REST API `api/Medreg/v1/persons` returning JSON",
        "rate_limit": "2 requests per second; follow `X-RateLimit-Remaining` headers",
        "auth": "API key optional; anonymous allowed with lower quotas",
        "legal_url": "https://www.admin.ch/gov/en/start/terms-and-conditions.html",
        "legal_notes": "Swiss federal terms demand attribution and forbid misuse.",
        "notes": "- Capture canton codes\n- Persist multilingual descriptions\n- Track professional card numbers",
    },
    {
        "path": "data/raw/europe/nordic/socialstyrelsen/README.md",
        "name": "Socialstyrelsen",
        "region": "Europe",
        "country": "Sweden",
        "coverage": "Excellent national coverage",
        "url": "https://legitimation.socialstyrelsen.se/",
        "method": "Form posts to `/api/search` returning JSON arrays",
        "rate_limit": "1 request per second; throttle heavier during 09:00-17:00 CET",
        "auth": "None",
        "legal_url": "https://www.socialstyrelsen.se/om-webbplatsen/anvandningsvillkor/",
        "legal_notes": "Comply with Swedish PSI licensing and cite Socialstyrelsen.",
        "notes": "- Fetch per starting letter to ensure completeness\n- Store Swedish titles and normalized English labels\n- Monitor API schema version header",
    },
    {
        "path": "data/raw/europe/nordic/valvira/README.md",
        "name": "Valvira",
        "region": "Europe",
        "country": "Finland",
        "coverage": "Excellent national coverage",
        "url": "https://www.valvira.fi/web/en/healthcare/professional_practice_rights/register",
        "method": "CSV export triggered via query parameters; fallback to HTML parsing",
        "rate_limit": "1 export per minute; portal queues longer jobs",
        "auth": "None",
        "legal_url": "https://www.valvira.fi/web/en/site-terms-of-use",
        "legal_notes": "Follow Finnish PSI rules and ensure GDPR-compliant storage.",
        "notes": "- Capture professional right type and validity ranges\n- Preserve bilingual Finnish/Swedish labels\n- Record export query parameters in metadata",
    },
    {
        "path": "data/raw/europe/nordic/danish_patient_safety_authority/README.md",
        "name": "Danish Patient Safety Authority",
        "region": "Europe",
        "country": "Denmark",
        "coverage": "Excellent national coverage",
        "url": "https://autregweb.sst.dk/",
        "method": "JSON endpoint `/api/Authorisation` paginated via OData",
        "rate_limit": "2 requests per second; respect `Retry-After`",
        "auth": "API key issued via open data portal recommended",
        "legal_url": "https://stps.dk/en/about-this-website/",
        "legal_notes": "Reuse permitted if crediting Danish Patient Safety Authority.",
        "notes": "- Capture authorization type and validity\n- Map municipality codes to ISO-3166-2\n- Store Danish characters in UTF-8",
    },
    {
        "path": "data/raw/europe/nordic/norwegian_directorate_of_health/README.md",
        "name": "Norwegian Directorate of Health",
        "region": "Europe",
        "country": "Norway",
        "coverage": "Excellent national coverage",
        "url": "https://www.helsedirektoratet.no/registrene/hpr",
        "method": "Download CSV via open data dataset `hpr-full`",
        "rate_limit": "Bulk export once daily; 100 MB file",
        "auth": "None",
        "legal_url": "https://www.helsedirektoratet.no/om-oss/personvern",
        "legal_notes": "Open data license NLOD; ensure attribution and change logs.",
        "notes": "- Store raw CSV compressed to save space\n- Track dataset version and checksum\n- Parse NOK-coded specialties",
    },
    {
        "path": "data/raw/oceania/australia/australian_health_practitioner_regulation_agency/README.md",
        "name": "Australian Health Practitioner Regulation Agency",
        "region": "Oceania",
        "country": "Australia",
        "coverage": "Excellent national coverage",
        "url": "https://www.ahpra.gov.au/Registration/Registers-of-Practitioners.aspx",
        "method": "Public search hitting `/api/PractitionerSearch` JSON endpoint",
        "rate_limit": "2 requests per second; nightly batches only",
        "auth": "None",
        "legal_url": "https://www.ahpra.gov.au/Footer/Privacy.aspx",
        "legal_notes": "Use data for transparency; do not imply AHPRA endorsement.",
        "notes": "- Capture conditions and undertakings\n- Track registration type and division\n- Align AHPRA numbers with canonical IDs",
    },
    {
        "path": "data/raw/oceania/new_zealand/medical_council_of_new_zealand/README.md",
        "name": "Medical Council of New Zealand",
        "region": "Oceania",
        "country": "New Zealand",
        "coverage": "Excellent national coverage",
        "url": "https://www.mcnz.org.nz/registration/list-of-registered-doctors/",
        "method": "Search interface with JSON endpoint `/umbraco/api/register/search`",
        "rate_limit": "1 request per second; comply with NZST quiet hours",
        "auth": "None",
        "legal_url": "https://www.mcnz.org.nz/privacy/",
        "legal_notes": "Respect MCNZ privacy statement and include attribution.",
        "notes": "- Capture scope of practice and vocational status\n- Save registration number and expiry\n- Monitor site for structural changes after 2024 redesign",
    },
    {
        "path": "data/raw/asia/japan/ministry_of_health_labour_and_welfare/README.md",
        "name": "Ministry of Health Labour and Welfare",
        "region": "Asia",
        "country": "Japan",
        "coverage": "Aggregated workforce statistics; limited individual access",
        "url": "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/iryou/kankei/index.html",
        "method": "Download PDF/XLS releases for physician census",
        "rate_limit": "Static files; refresh semi-annually",
        "auth": "None",
        "legal_url": "https://www.mhlw.go.jp/english/policy.html",
        "legal_notes": "Follow Japanese government open data license; cite MHLW.",
        "notes": "- Convert PDF tables to structured CSV\n- Map prefecture codes to ISO standards\n- Flag data as aggregate only (no direct licensing)",
    },
    {
        "path": "data/raw/asia/south_korea/korean_medical_association/README.md",
        "name": "Korean Medical Association",
        "region": "Asia",
        "country": "South Korea",
        "coverage": "Partial; professional association register",
        "url": "https://www.kma.org/",
        "method": "Member search portal requiring form POST and possible CAPTCHA",
        "rate_limit": "1 request every 3 seconds; manual verification required",
        "auth": "Login for advanced search; basic lookup anonymous",
        "legal_url": "https://www.kma.org/guide/privacy.do",
        "legal_notes": "Association terms forbid commercial reuse; obtain written permission before automation.",
        "notes": "- Document CAPTCHA handling strategy\n- Capture KMA member number for joins\n- Treat data as supplemental, not primary licensing",
    },
    {
        "path": "data/raw/asia/india/national_medical_commission/README.md",
        "name": "National Medical Commission",
        "region": "Asia",
        "country": "India",
        "coverage": "Improving; national register with occasional outages",
        "url": "https://www.nmc.org.in/MCIRest/verifyDetails",
        "method": "REST endpoint taking registration number or name returning JSON",
        "rate_limit": "1 request per second; throttle lower due to server instability",
        "auth": "None but requires CAPTCHA token per session",
        "legal_url": "https://www.nmc.org.in/terms-of-use",
        "legal_notes": "Usage subject to Indian IT Act; cite NMC and avoid data resale.",
        "notes": "- Rotate IPs to mitigate throttling\n- Store CAPTCHA solving logs\n- Normalize state medical council codes",
    },
    {
        "path": "data/raw/asia/singapore/singapore_medical_council/README.md",
        "name": "Singapore Medical Council",
        "region": "Asia",
        "country": "Singapore",
        "coverage": "Excellent national register",
        "url": "https://prs.moh.gov.sg/prs/internet/profSearch/mcPractitionerSearch.action",
        "method": "POST form returning HTML table; parse with BeautifulSoup",
        "rate_limit": "1 request per second; respect MOH monitoring",
        "auth": "None",
        "legal_url": "https://www.moh.gov.sg/terms-of-use",
        "legal_notes": "Reuse only for verification; cite SMC and MOH.",
        "notes": "- Capture practice place type and register category\n- Track conditional registrations\n- Localize timezone for updated_at field",
    },
    {
        "path": "data/raw/asia/hong_kong/medical_council_of_hong_kong/README.md",
        "name": "Medical Council of Hong Kong",
        "region": "Asia",
        "country": "Hong Kong",
        "coverage": "Good national register",
        "url": "https://www.mchk.org.hk/english/list/list.html",
        "method": "Download full register XLS (`printDoc/listD.pdf` alternative) and parse",
        "rate_limit": "Static file; refresh monthly",
        "auth": "None",
        "legal_url": "https://www.mchk.org.hk/english/notice/disclaimer.html",
        "legal_notes": "Respect disclaimer; data for public reference only.",
        "notes": "- Convert XLS to CSV with utf-8 encoding\n- Capture specialty and qualification notes\n- Track bilingual fields",
    },
    {
        "path": "data/raw/middle_east/israel/ministry_of_health_israel/README.md",
        "name": "Ministry of Health Israel",
        "region": "Middle East",
        "country": "Israel",
        "coverage": "Good but fragmented",
        "url": "https://practitioners.health.gov.il/Practitioners/",
        "method": "SPA calling `/api/Practitioner` REST endpoints",
        "rate_limit": "1 request per second; site enforces throttling via gateway",
        "auth": "None, but requires Hebrew locales in headers",
        "legal_url": "https://www.gov.il/en/terms-of-use",
        "legal_notes": "Government ToU require lawful use and prohibit bulk republication without consent.",
        "notes": "- Capture license class and issuing office\n- Store Hebrew and English transliterations\n- Track practitioners lacking public consent flag",
    },
    {
        "path": "data/raw/middle_east/united_arab_emirates/dubai_health_authority/README.md",
        "name": "Dubai Health Authority",
        "region": "Middle East",
        "country": "United Arab Emirates",
        "coverage": "Good but fragmented",
        "url": "https://services.dha.gov.ae/en/Pages/ProfessionalSearch.aspx",
        "method": "ASP.NET form posting to `ProfessionalSearchService.svc/GetProfessionals`",
        "rate_limit": "1 request every 2 seconds; DHA blocks faster traffic",
        "auth": "Requires session cookie and hidden viewstate tokens",
        "legal_url": "https://www.dha.gov.ae/en/Pages/PrivacyPolicy.aspx",
        "legal_notes": "DHA policy prohibits unauthorized commercial reuse; seek approval for automation.",
        "notes": "- Capture license type, facility, and expiration\n- Store emirate/location metadata\n- Coordinate with DOH Abu Dhabi job to dedupe",
    },
    {
        "path": "data/raw/middle_east/united_arab_emirates/department_of_health_abu_dhabi/README.md",
        "name": "Department of Health Abu Dhabi",
        "region": "Middle East",
        "country": "United Arab Emirates",
        "coverage": "Good but fragmented",
        "url": "https://www.doh.gov.ae/en/Professionals/Healthcare-Professionals/Licensing",
        "method": "Shafaf portal REST API `/api/publicsearch` with JSON pagination",
        "rate_limit": "1 request per second; API includes explicit quota headers",
        "auth": "API key issued upon request for higher limits",
        "legal_url": "https://www.doh.gov.ae/en/terms-and-conditions",
        "legal_notes": "Terms require prior written consent for automated collection.",
        "notes": "- Coordinate with DHA dataset for UAE-wide dedupe\n- Capture facility affiliations\n- Track data lineage for FOI compliance",
    },
    {
        "path": "data/raw/africa/south_africa/health_professions_council_of_south_africa/README.md",
        "name": "Health Professions Council of South Africa",
        "region": "Africa",
        "country": "South Africa",
        "coverage": "Public lookup with limited bulk access",
        "url": "https://hpcsaonline.co.za/Registrations/Practitioner",
        "method": "Form posts with CAPTCHA, returns HTML tables",
        "rate_limit": "Manual cadence; plan scripted pulls via FOI exports",
        "auth": "reCAPTCHA plus session cookies",
        "legal_url": "https://www.hpcsa.co.za/?contentId=151",
        "legal_notes": "Comply with POPIA; automated access may require authorization.",
        "notes": "- Document FOI export process\n- Store HPCSA number and profession\n- Capture disciplinary flags when available",
    },
    {
        "path": "data/raw/africa/nigeria/medical_and_dental_council_of_nigeria/README.md",
        "name": "Medical and Dental Council of Nigeria",
        "region": "Africa",
        "country": "Nigeria",
        "coverage": "Registry exists but limited",
        "url": "https://portal.mdcngov.ng/verify",
        "method": "Form submission calling `/api/Practitioner/Verify`",
        "rate_limit": "1 request every 3 seconds; manual CAPTCHA solving",
        "auth": "reCAPTCHA token plus verification code",
        "legal_url": "https://www.mdcngov.ng/privacy-policy/",
        "legal_notes": "Nigerian privacy policy restricts reuse without consent.",
        "notes": "- Capture license category and validity\n- Record evidence of consent for automation\n- Track outages and needed manual interventions",
    },
    {
        "path": "data/raw/africa/kenya/kenya_medical_practitioners_and_dentists_council/README.md",
        "name": "Kenya Medical Practitioners and Dentists Council",
        "region": "Africa",
        "country": "Kenya",
        "coverage": "Public registries with occasional downtime",
        "url": "https://kmpdc.go.ke/online-services/registers/",
        "method": "Download PDF registers per profession; convert to CSV",
        "rate_limit": "Static files; refresh quarterly",
        "auth": "None",
        "legal_url": "https://kmpdc.go.ke/privacy-policy/",
        "legal_notes": "Respect Kenyan data protection law; cite KMPDC.",
        "notes": "- Automate PDF to CSV conversion\n- Capture council number and facility\n- Track incomplete digitization for dentists",
    },
    {
        "path": "data/raw/latin_america/brazil/conselho_federal_de_medicina/README.md",
        "name": "Conselho Federal de Medicina",
        "region": "Latin America",
        "country": "Brazil",
        "coverage": "Good national coverage",
        "url": "https://portal.cfm.org.br/busca-medicos/",
        "method": "AJAX search hitting `/wp-admin/admin-ajax.php?action=buscar_medicos`",
        "rate_limit": "1 request per second; abide by robots.txt",
        "auth": "None",
        "legal_url": "https://portal.cfm.org.br/termos-de-uso/",
        "legal_notes": "Brazilian LGPD applies; cite CFM and honor opt-outs.",
        "notes": "- Capture CRM number and UF (state)\n- Store specialty board recognition\n- Track consent status for publishing contact info",
    },
    {
        "path": "data/raw/latin_america/argentina/ministerio_de_salud_argentina/README.md",
        "name": "Ministerio de Salud Argentina",
        "region": "Latin America",
        "country": "Argentina",
        "coverage": "Good national coverage",
        "url": "https://sisa.msal.gov.ar/sisa/",
        "method": "SOAP-like API for Registro Federal de Profesionales de la Salud (REFEPS)",
        "rate_limit": "1 request per second; tokens expire every 30 minutes",
        "auth": "Requires API key tied to institutional agreement",
        "legal_url": "https://www.argentina.gob.ar/aviso-legal",
        "legal_notes": "National transparency rules still require attribution and lawful use.",
        "notes": "- Store REFEPS IDs and province codes\n- Capture specialty authorizations\n- Track contract requirements for API key renewal",
    },
    {
        "path": "data/raw/latin_america/chile/superintendencia_de_salud/README.md",
        "name": "Superintendencia de Salud",
        "region": "Latin America",
        "country": "Chile",
        "coverage": "Good national coverage",
        "url": "https://www.supersalud.gob.cl/servicios/666/w3-propertyvalue-3811.html",
        "method": "Download XLS registers for health professionals",
        "rate_limit": "Static files; refresh monthly",
        "auth": "None",
        "legal_url": "https://www.supersalud.gob.cl/servicios/666/w3-propertyvalue-1571.html",
        "legal_notes": "Reuse under Chilean transparency law with attribution.",
        "notes": "- Convert XLS to UTF-8 CSV\n- Capture Superintendencia specialty classifications\n- Track revisions by version number",
    },
    {
        "path": "data/raw/international/meta/world_directory_of_medical_schools/README.md",
        "name": "World Directory of Medical Schools",
        "region": "International",
        "country": "International",
        "coverage": "Global school-level registry",
        "url": "https://search.wdoms.org/",
        "method": "GraphQL API powering school search",
        "rate_limit": "1 request per second; site monitors abuse",
        "auth": "API token required for bulk access (apply via WDOMS)",
        "legal_url": "https://search.wdoms.org/home/termsofuse",
        "legal_notes": "Bulk reuse requires agreement with WFME/FAIMER.",
        "notes": "- Use as join table linking physician training\n- Store school identifiers and program status\n- Track curriculum language for enrichment",
    },
    {
        "path": "data/raw/international/meta/world_health_organization/README.md",
        "name": "World Health Organization",
        "region": "International",
        "country": "International",
        "coverage": "Workforce density and macro indicators",
        "url": "https://ghoapi.azureedge.net/api/",
        "method": "REST API for Global Health Observatory datasets",
        "rate_limit": "100 requests per minute default quota",
        "auth": "None",
        "legal_url": "https://www.who.int/about/policies/privacy",
        "legal_notes": "Use data consistent with WHO open license and cite WHO.",
        "notes": "- Pull physician density indicators per country\n- Store metadata describing indicator codes\n- Join to canonical country table for analytics",
    },
    {
        "path": "data/raw/international/meta/oecd/README.md",
        "name": "OECD",
        "region": "International",
        "country": "International",
        "coverage": "Physician per capita and specialty statistics",
        "url": "https://stats.oecd.org/",
        "method": "RESTful SDMX queries via `https://stats.oecd.org/SDMX-JSON/data/`",
        "rate_limit": "Unlimited for small pulls; throttle to 10 requests per minute for bulk",
        "auth": "None",
        "legal_url": "https://www.oecd.org/termsandconditions/",
        "legal_notes": "OECD license permits non-commercial reuse with attribution.",
        "notes": "- Document SDMX query templates\n- Store dataset code, measure, and unit\n- Align country codes with ISO alpha-3",
    },
]


def main() -> None:
    for entry in SOURCES:
        target = BASE_DIR / entry["path"]
        target.parent.mkdir(parents=True, exist_ok=True)
        content = TEMPLATE.format(**entry)
        target.write_text(content, encoding="utf-8")
        print(f"Updated {target.relative_to(BASE_DIR)}")


if __name__ == "__main__":
    main()
